name: Ansible runner via Github Action
run-name: ${{ github.actor }} is starting the Ansible Runner 🚀
on: [push]
jobs:
  Ansible-Run:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install software-properties-common
      - run: sudo add-apt-repository --yes --update ppa:ansible/ansible
      - run: sudo apt install ansible
      - run: ls ${{ github.workspace }}

