name: Ansible runner via Github Action
run-name: ${{ github.actor }} is testing out the Ansible Runner 🚀
on: [push]
jobs:
  Ansible-Runner:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Actions checkout v2 run ansible
        run: ansible-playbook play-azure.yaml
