name: Ansible runner via Github Action
run-name: ${{ github.actor }} is testing out the Ansible Runner 🚀
on: [push]
jobs:
  Update-Node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm ci --force
      - name: apt update
      - run: sudo apt update
      - name: software-properties-common install
      - run: sudo apt install software-properties-common
      - name: PPA repo add 
      - run: sudo add-apt-repository --yes --update ppa:ansible/Ansible
      - name: ansible install
      - run: sudo apt install ansible

