
name: Node Workflow
run-name: ${{ github.actor }} is starting the Node Workflow 🚀
on: [push]
jobs:
  Update-Node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm ci --force
